name: CI

on:
  
  push:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Build
        run: |
          chmod +x gradlew 
          ./gradlew build 
          ls -ltr
          
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with: 
          java-version: 17
          distribution: 'temurin'

          
      - name: SonarCloud Analysis
        run: |
          chmod +x gradlew 
          ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD }} 
     
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: 'pet-clinic'
          path: '.'
          format: 'HTML' 
      
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
