name: CI

on:
  
  push:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Build
        run: |
          chmod +x gradlew 
          ./gradlew build 
          ls -ltr
          
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with: 
          java-version: 17
          distribution: 'temurin'

          
      - name: SonarCloud Analysis
        run: |
          chmod +x gradlew 
          ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD }} 
     
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'final-lab'
          path: '.'
          format: 'HTML' 
      
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: | 
          docker build --tag ivanpizarroq/final-lab:latest .
          docker images
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ivanpizarroq/final-lab:latest'
          format: 'table'
          #exit-code: 1 PARAMETRO PARA QUIEBRE DE PIPELINE 

      - name: Docker Push
        run: |
          docker push ivanpizarroq/final-lab 

  deploy: 
    runs-on: self-hosted 
    needs: build
    steps: 

    #- uses: actions/checkout@v3
    #- name: Set PowerShell Execution Policy
    #  run: |
    #    Set-ExecutionPolicy Unrestricted
    - name: Pull de la Imagen Docker
      run: |
        docker pull ivanpizarroq/final-lab:latest
    - name: Despliegue Aplicaion
      run: |
        docker run -p 8081:80 --name final-lab-deploy -d ivanpizarroq/final-lab:latest 

    - name: Sleep
      run: | 
        sleep 30

    #- name: OWASP ZAP Scan
     # uses: zaproxy/action-baseline@v0.11.0
      #with:
       # target: 'http://localhost:8085/'

    - name: OWASP ZAP Scan
      run: |
        docker run -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:80


